version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: microservices_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - DATA_SERVICE_URL=http://data-service:3003
    depends_on:
      - auth-service
      - user-service
      - data-service
    networks:
      - microservices-network

  # Auth Service
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=microservices_db
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mysql
    networks:
      - microservices-network

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=microservices_db
    depends_on:
      - mysql
    networks:
      - microservices-network

  # Data Service
  data-service:
    build: ./data-service
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=microservices_db
    depends_on:
      - mysql
    networks:
      - microservices-network

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge